### ISSUE TITLE
CO-RE feature detection not working

### ISSUE THREAD

**Issue by pmmccorm** [libbpf/bpftool#14]
On Ubuntu focal I see:
```
$ make
...                        libbfd: [ on  ]
...        disassembler-four-args: [ on  ]
...                          zlib: [ on  ]
...                        libcap: [ on  ]
...               clang-bpf-co-re: [ OFF ]
```

After looking in Makefile.features it is looking for BTF_KIND_VAR, but I don't see that:

```

$ clang --version
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

[~/scm/bpftool/src (master)]
$ printf '%s\n' 'struct s { int i; } __attribute__((preserve_access_index)); struct s foo;' | clang -g -target bpf -S -o - -x c -  | grep BTF_KIND_
        .long   1                       # BTF_KIND_STRUCT(id = 1)
        .long   5                       # BTF_KIND_INT(id = 2)
```

Am I not configured correctly or should this check be more loose?

**Comment by pmmccorm** [comment]
I looked through the CI building: build #9 does do this, but more recent ones do.

**Comment by qmonnet** [comment]
> Am I not configured correctly or should this check be more loose?

Hi, I think the check is correct. Command `bpftool prog profile` [needs clang to support generating BTF for global variables](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=14e5728ff8176d4d5924b0bf5ab9b1c94d6b3381) (hence the `BTF_KIND_VAR`), so I don't think we can loosen the restriction.

What's your clang version? On focal I'd expect 1.10 by default, but you should be able to get `clang-11` or `clang-12` from the repos and both should work.

> I looked through the CI building: build https://github.com/libbpf/bpftool/pull/9 does do this, but more recent ones do.

Sorry, I'm not sure what you mean here?

**Comment by qmonnet** [comment]
I'll close the issue for now, let me know if the above did not answer correctly to your questions.
