### ISSUE TITLE
Missing bpffs mount when pinning maps for prog load (`pinmaps`)

### ISSUE THREAD

**Issue by qmonnet** [libbpf/bpftool#146]
Looking at the code around mounting the bpffs in bpftool's `prog.c`, I see that we don't call `mount_bpffs_for_pin()` for the directory where the user wants to pin maps, if `pinmaps` is passed:

```c
	err = mount_bpffs_for_pin(pinfile, !first_prog_only);
	if (err)
		goto err_close_obj;

	if (first_prog_only) {
		prog = bpf_object__next_program(obj, NULL);
		if (!prog) {
			p_err("object file doesn't contain any bpf program");
			goto err_close_obj;
		}

		if (auto_attach)
			err = auto_attach_program(prog, pinfile);
		else
			err = bpf_obj_pin(bpf_program__fd(prog), pinfile);
		if (err) {
			p_err("failed to pin program %s",
			      bpf_program__section_name(prog));
			goto err_close_obj;
		}
	} else {
		if (auto_attach)
			err = auto_attach_programs(obj, pinfile);
		else
			err = bpf_object__pin_programs(obj, pinfile);
		if (err) {
			p_err("failed to pin all programs");
			goto err_close_obj;
		}
	}

	if (pinmaps) {

		// XXX No guarantee that the bpffs is mounted for directory pinmaps, here

		err = bpf_object__pin_maps(obj, pinmaps);
		if (err) {
			p_err("failed to pin all maps");
			goto err_unpin;
		}
	}
```

I haven't tested it though, but I expect the map pinning to fail if we pass a `pinmaps` directory that is not under the bpffs.

_Originally posted by @qmonnet in https://github.com/libbpf/bpftool/issues/100#issuecomment-1978460616_

**Comment by chentao-kernel** [comment]
Hi, qmonnet
The problem seems still exist in 6.10-rc4, when i run a test case:
```
libbpf: specified path /home/ubuntu/test/sock_ops_map is not on BPF FS                                                                       │
Error: failed to pin all maps
```
No one fixes it right？Maybe i can submit a patch

**Comment by qmonnet** [comment]
Correct, nobody has fixed the issue, and a patch is welcome, thanks! :)

**Comment by chentao-kernel** [comment]
> Correct, nobody has fixed the issue, and a patch is welcome, thanks! :)

Thank you for your reply,  i will send it later

**Comment by qmonnet** [comment]
https://lore.kernel.org/bpf/20240702131150.15622-1-chen.dylane@gmail.com/t/#u

**Comment by qmonnet** [comment]
Daniel just merged the patch to bpf-next, thanks a lot! It will land in this repo at the next sync.

**Comment by chentao-kernel** [comment]
> Daniel just merged the patch to bpf-next, thanks a lot! It will land in this repo at the next sync.



> Daniel just merged the patch to bpf-next, thanks a lot! It will land in this repo at the next sync.

Hi qmonnet,
Thank you for merging my patch!
