### ISSUE TITLE
btf dump with the format of /sys/kernel/btf/vmlinux

### ISSUE THREAD

**Issue by vincentmli** [libbpf/bpftool#163]
Hi @qmonnet :)

I noticed in running Linux system with BTF enabled, there is `/sys/kernel/btf/vmlinux` mounted, but the format of `/sys/kernel/btf/vmlinux` is in unreadable form. could bpftool used to dump the same format of `/sys/kernel/btf/vmlinux` from kernel vmlinux image encoded with BTF? the bpftool format `raw` or `c` is different than `/sys/kernel/btf/vmlinux`.

why I need this? because I am building external kernel module for a target kernel  in chroot environment in a  build host, the chroot build process always uses host `/sys/kernel/btf/vmlinux` for the external kernel module, not target kernel vmlinux btf.

it appears pahole is the tool to do this sort of thing, any clue to use pahole to do this would be greatly appreciated !

**Comment by qmonnet** [comment]
Hey Vincent, it's been a while :)

Not sure I follow, are you asking for `bpftool btf dump file /sys/kernel/btf/vmlinux`?

```console
$ bpftool btf dump file /sys/kernel/btf/vmlinux | head
[1] INT 'long unsigned int' size=8 bits_offset=0 nr_bits=64 encoding=(none)
[2] PTR '(anon)' type_id=5
[3] CONST '(anon)' type_id=2
[4] INT 'char' size=1 bits_offset=0 nr_bits=8 encoding=(none)
[5] CONST '(anon)' type_id=4
[6] INT 'unsigned int' size=4 bits_offset=0 nr_bits=32 encoding=(none)
[7] INT 'signed char' size=1 bits_offset=0 nr_bits=8 encoding=SIGNED
[8] TYPEDEF '__u8' type_id=9
[9] INT 'unsigned char' size=1 bits_offset=0 nr_bits=8 encoding=(none)
[10] INT 'short int' size=2 bits_offset=0 nr_bits=16 encoding=SIGNED

$ bpftool btf dump file /sys/kernel/btf/vmlinux format c | head  
#ifndef __VMLINUX_H__
#define __VMLINUX_H__

#ifndef BPF_NO_PRESERVE_ACCESS_INDEX
#pragma clang attribute push (__attribute__((preserve_access_index)), apply_to = record)
#endif

typedef unsigned char __u8;

typedef short unsigned int __u16;
```

**Comment by vincentmli** [comment]
> Hey Vincent, it's been a while :)
> 
> Not sure I follow, are you asking for `bpftool btf dump file /sys/kernel/btf/vmlinux`?
> 

no, sorry to confuse you, let me explain in more detail. https://github.com/luainkernel/lunatik project had external kernel module luaxdp that export kfunc `bpf_luaxdp_run` that is required to do Lua scripting for XDP program. the lunatik external kernel modules build, load and runs fine in normal Ubuntu system. 

now I want to add lunatik luaxdp kernel module to my project https://github.com/vincentmli/BPFire which is fork of IPFire but with kernel eBPF features enabled. BPFire/IPFire has chroot build environment where everything including kernel can be build from scratch from the source code.

 my issue is when I build lunatik luaxdp kernel module for BPFire kernel in chroot environment,  the luaxdp kernel module build requires `/sys/kernel/btf/vmlinux`, but the chroot mount host `/sys/kernel/btf/vmlinux` for luaxdp kernel module build, this result in kernel module BTF mismatch and kuncs not registered in target running kernel, error below when I load the luaxdp kernel module in target running system

```
[root@bpfire-2 lua]# dmesg

[  330.411665] lunatik: loading out-of-tree module taints kernel.
[  330.411680] lunatik: module verification failed: signature and/or required key missing - tainting kernel
[  330.433955] Kernel module BTF mismatch detected, BTF debug info may be unavailable for some modules
[  330.767701] missing module BTF, cannot register kfuncs
```

so I think what I needed is to create a `/sys/kernel/btf/vmlinux` from the target built kernel vmlinux image and use that when build luaxdp kernel module in chroot build environment, the question is how I can create format of `/sys/kernel/btf/vmlinux` file from target build kernel vmlinux image.  let me know if you are still confused :).  I have a long discussion with lunatik maintainer https://github.com/luainkernel/lunatik/issues/189 that is too long to read

**Comment by qmonnet** [comment]
So basically you want to regenerate the BTF info from the kernel in your chroot environment, right?

I don't think the procedure is documented, but I'd look at `gen_btf` in [scripts/link-vmlinux.sh](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/link-vmlinux.sh?h=v6.11#n108) (and some flags defined in [scripts/Makefile.btf](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/Makefile.btf?h=v6.11)); although I'm not sure through what mechanism the BTF file is exposed via the sysfs after that, but torvalds/linux@341dfcf8d78eaa3a2dc96dea06f0392eb2978364 would likely provide more info.

Does this help?

**Comment by vincentmli** [comment]
yes, that looks to be the information I am looking for, I will read about it, thanks for the guidance! :)
