### ISSUE TITLE
Failed to build bpftool from source

### ISSUE THREAD

**Issue by chenhengqi** [libbpf/bpftool#17]
```shell
clang \
        -I. \
        -I/home/ubuntu/bpf/bpftool/include/uapi/ \
        -I/home/ubuntu/bpf/bpftool/src/bootstrap/libbpf/include \
        -g -O2 -Wall -target bpf -c skeleton/pid_iter.bpf.c -o pid_iter.bpf.o
skeleton/pid_iter.bpf.c:47:14: error: incomplete definition of type 'struct bpf_perf_link'
        perf_link = container_of(link, struct bpf_perf_link, link);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by qmonnet** [comment]
Hi, thanks for the report!
What's your kernel version, please? I guess it is lower than 5.15? It seems that commit [cbdaf71f7e65](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=cbdaf71f7e65a45d6e96378ee7bfe3da39c30908) introduced requirements for [recent structures](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=b89fbfbb854c9afc3047e8273cc3a694650b802e) to be present in kernel's BTF when compiling :/.

**Comment by chenhengqi** [comment]
Yes, I tried it on 5.4 and 5.11.

**Comment by withlin** [comment]
+1  `5.11.0-49-generic`

**Comment by qmonnet** [comment]
Thanks for the reports!

Since https://github.com/libbpf/bpftool/commit/d97300d3565e99d9fea06d1875935234796f4096, kernel 5.15 is a requirement for building bpftool with all its features. The definition may also be missing if the kernel of the host has not been compiled with `CONFIG_PERF_EVENTS`.

Workarounds:
- Work with an older version (the latest release should not include this commit and should compile fine).
- Disable the “skeletons” feature (`feature-clang-bpf-co-re`), but there's currently no clean way to do this (I'm planning to add Makefile options for that when I have some cycles) so you'll have to edit the Makefile manually.

I'll try to submit a fix upstream.

**Comment by chenhengqi** [comment]
```diff
diff --git a/src/Makefile b/src/Makefile
index bffd4e7..5fc927e 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -125,7 +125,7 @@ all: $(OUTPUT)bpftool
 
 BFD_SRCS = jit_disasm.c
 
-SRCS = $(filter-out $(BFD_SRCS),$(wildcard *.c))
+SRCS = $(filter-out $(BFD_SRCS) pids.c,$(wildcard *.c))
 
 ifeq ($(feature-libbfd),1)
   LIBS += -lbfd -ldl -lopcodes
```

**Comment by qmonnet** [comment]
I haven't managed to found a fix myself (I was missing the `...___local` change), but I believe that the patch currently discussed on the mailing list should address the issue.

https://lore.kernel.org/bpf/20220421003152.339542-3-alobakin@pm.me/T/#u

**Comment by liusy58** [comment]
> ```diff
> diff --git a/src/Makefile b/src/Makefile
> index bffd4e7..5fc927e 100644
> --- a/src/Makefile
> +++ b/src/Makefile
> @@ -125,7 +125,7 @@ all: $(OUTPUT)bpftool
>  
>  BFD_SRCS = jit_disasm.c
>  
> -SRCS = $(filter-out $(BFD_SRCS),$(wildcard *.c))
> +SRCS = $(filter-out $(BFD_SRCS) pids.c,$(wildcard *.c))
>  
>  ifeq ($(feature-libbfd),1)
>    LIBS += -lbfd -ldl -lopcodes
> ```

This can compile successfully but everytime I execute `sudo bpftool prog show`, `segmentation fault` pops up.

**Comment by adamzhoul** [comment]
same issue. +1

**Comment by qmonnet** [comment]
I re-submitted the patches today (at https://lore.kernel.org/bpf/20230512103354.48374-1-quentin@isovalent.com/t/#u).

**Comment by qmonnet** [comment]
Apologies, this had taken more time than I expected - or than it should have. At last, we have [the fix merged in bpf-next](https://lore.kernel.org/bpf/168902882242.25605.6497606191994518025.git-patchwork-notify@kernel.org/T/#m5566395b6b3ca109ec256b99d2a8404f5f316624). I'll pull it in this repo at the next sync.
