### ISSUE TITLE
Building with clang breaks feature detection due to -Werror

### ISSUE THREAD

**Issue by hhoffstaette** [libbpf/bpftool#170]
## Reporting an issue

- [x] I considered whether to report to the BPF mailing list first

## Environment

- bpftool version: git master
- Linux kernel version: 6.11.4
- (optionally) clang/LLVM version: 19.1.1

## Describe the bug

I noticed another inconsistency between the kernel-tree build and the mirror regarding feature detection when building with clang as compiler. clang is not the actual problem, though.

Building with `make CC=clang V=1 feature-libbfd=1 feature-llvm=0` works fine in the kernel tree and does all the right things. For some reason passing VF=1 does NOT print the details of the feature detection, but at least the built bpftool is correct, so I assume the feature detection worked correctly.

Doing so in the mirror tree gives:
```
Makefile.feature:34: Probing: feature-clang-bpf-co-re
Makefile.feature:35: printf '%s\n' 'struct s { int i; } __attribute__((preserve_access_index)); struct s foo = {};' | clang -g -target bpf -S -o - -x c -  | grep -q BTF_KIND_VAR && (echo 1 && >&2 echo result: 1) || (echo 0 && >&2 echo result: 0)
result: 1
Makefile.feature:54: Probing: feature-libbfd
Makefile.feature:55: printf '%b\n' '#include <bfd.h>\n' 'int main(void) {' '	bfd_demangle(0, 0, 0);' '	return 0;' '}' | clang  -Wall -Werror -x c -DPACKAGE='"bpftool"' - -lbfd -ldl -o /dev/null >/dev/null && (echo 1 && >&2 echo result: 1) || (echo 0 && >&2 echo result: 0)
result: 1
Makefile.feature:86: Probing: feature-disassembler-four-args
Makefile.feature:87: printf '%b\n' '#include <dis-asm.h>\n' 'int main(void) {' '	disassembler((enum bfd_architecture)0, 0, 0, NULL);' '	return 0;' '}' | clang  -Wall -Werror -x c -DPACKAGE='"bpftool"' - -lbfd -lopcodes -S -o - >/dev/null && (echo 1 && >&2 echo result: 1) || (echo 0 && >&2 echo result: 0)
clang: error: -lbfd: 'linker' input unused [-Werror,-Wunused-command-line-argument]
clang: error: -lopcodes: 'linker' input unused [-Werror,-Wunused-command-line-argument]
result: 0
Makefile.feature:100: Probing: feature-disassembler-styled
Makefile.feature:101: printf '%b\n' '#include <dis-asm.h>\n' 'int main(void) {' '	init_disassemble_info(NULL, 0, NULL, NULL);' '	return 0;' '}' | clang  -Wall -Werror -x c -DPACKAGE='"bpftool"' - -lbfd -lopcodes -S -o - >/dev/null && (echo 1 && >&2 echo result: 1) || (echo 0 && >&2 echo result: 0)
clang: error: -lbfd: 'linker' input unused [-Werror,-Wunused-command-line-argument]
clang: error: -lopcodes: 'linker' input unused [-Werror,-Wunused-command-line-argument]
result: 0
Makefile.feature:120: Probing: feature-libcap
Makefile.feature:121: printf '%b\n' '#include <sys/capability.h>\n' 'int main(void) {' '	cap_free(0);' '	return 0;' '}' | clang  -Wall -Werror -x c - -lcap -S -o - >/dev/null && (echo 1 && >&2 echo result: 1) || (echo 0 && >&2 echo result: 0)
clang: error: -lcap: 'linker' input unused [-Werror,-Wunused-command-line-argument]
result: 0
```
The build will continue and eventually fail because the libbfd detection was actually not successful.

I've worked around this for now by filtering the overly aggressive & fragile `-Werror` from Makefile.feature.

**Comment by qmonnet** [comment]
Thanks!
Would it work if we remove the error related to the unused arguments instead? Something like `-Wno-error=unused-command-line-argument` I think. The presence of unused arguments isn't relevant for these probes.

**Comment by hhoffstaette** [comment]
> Thanks! Would it work if we remove the error related to the unused arguments instead? Something like `-Wno-error=unused-command-line-argument` I think. The presence of unused arguments isn't relevant for these probes.

Sure - I gave that a try via an additional EXTRA_CFLAGS=-Wno-error=unused-command-line-argument and it worked too, as expected. After all the problem here is really just that clang-as-linker also warns about the unused libs when linking, unlike gcc.

**Comment by hhoffstaette** [comment]
Eh, of course now I see that there's a section at the beginning of Makefile.feature that already does this..for the llvm feature. So just remove the `ifneq ($(LLVM),)` guard and always add the flag.

**Comment by qmonnet** [comment]
> For some reason passing VF=1 does NOT print the details of the feature detection

There's no mechanism to show probing results when building bpftool from the kernel tree. You'd have to go to `tools/build/feature`, where the feature probes are defined, and play with the build system to get more detailed results.
