### ISSUE TITLE
bpftool btf kfunc show feature

### ISSUE THREAD

**Issue by chentao-kernel** [libbpf/bpftool#173]
## Reporting an issue
Hi, qmonnet, now may kfuncs supported in the uptream, especially when sched_ext merged.Can we support bpftool to show
all kfuncs supported on the kernel, and it is convenient for developers. Maybe we can parse it from /proc/kallsyms, the kfunc symbol has the prefix with "__BTF_ID__func__"
![image](https://github.com/user-attachments/assets/f83abeac-2634-4bc2-8e07-ce1882673341)

So can we add a subcommand like:
`bpftool btf kfunc`

- [ ] I considered whether to report to the BPF mailing list first

**Comment by qmonnet** [comment]
Hey Tao!

Bpftool is now able to dump the prototype for available kfuncs when doing a `bpftool btf dump <vmlinux> format c`, see 3e0251a4bcebc967c15e7ce940d20b7e59d3d1d4. Would it solve your use case?

**Comment by chentao-kernel** [comment]
> Hey Tao!
> 
> Bpftool is now able to dump the prototype for available kfuncs when doing a `bpftool btf dump <vmlinux> format c`, see [3e0251a](https://github.com/libbpf/bpftool/commit/3e0251a4bcebc967c15e7ce940d20b7e59d3d1d4). Would it solve your use case?

Year, this patch is useful for me , thanks a lot!
