### ISSUE TITLE
Question: Getting map type info from bpf programs.

### ISSUE THREAD

**Issue by dushyantbehl** [libbpf/bpftool#46]
Hi,
I am working on a small tool which needs to identify map type (HASH/ARRAY etc) from bpf programs. I have seen BTF which is able to provide type of the key and value of the map but not the type of the map itself (which is the value of the map type variable).
So what I want to ask is is there a way to identity the type of map being used by looking at the BPF programs. 

Not sure if this is the correct place to ask this question, if not please let me know.
Thanks in advance.

**Comment by qmonnet** [comment]
Hi, I'd say it depends on when you consider the BPF program. Is it in the ELF object file before it gets loaded into the kernel? In that case you can probably retrieve the map metadata, including type, from the relevant ELF section. Or is it after the program has been loaded into the kernel? In that case, you should be able to retrieve the list of map ids that the program is using (see how `bpftool prog show` displays the ids of the maps used by the programs). From these ids, you can get the map information, including the type, through a `bpf()` syscall (see for example `bpf_map_get_fd_by_id()` followed by `bpf_obj_get_info_by_fd()` in libbpf).

Does this help?

**Comment by dushyantbehl** [comment]
Thanks for the quick reply @qmonnet

I am considering it before loading in the kernel and have looked at the ELF.
Am I correct in assuming that the map type is the first word at the start of the map section?

**Comment by qmonnet** [comment]
I think it's the first 64-bit integer, yes, see [this description (at least for legacy map definitions)](https://github.com/dthaler/ebpf-docs-1/blob/f04abcbd8b2b9126b0b02adfa36937835c3f48a3/rst/elf.rst#data-sections). I don't remember for BTF maps, probably the case as well. You can probably check that by analysing your object files, or looking at the related code in one of the eBPF libraries out there.

**Comment by dushyantbehl** [comment]
Thanks @qmonnet..I'll close the issue
