### ISSUE TITLE
Skeletons: Support cross-compiling towards architectures with different endianness

### ISSUE THREAD

**Issue by qmonnet** [libbpf/bpftool#81]
> TL;DR: When cross-compiling, host little-endian bootstrap bpftool cannot
open a big-endian ELF to generate a skeleton from it and build target
big-endian bpftool.
>
> Long version: Currently, bpftool's Makefile compiles the
skeleton-related programs (skeletons/*.bpf.c) without paying attention
to the target architecture. When cross-compiling, say on a host with LE
for a target with BE, this leads to runtime failure on "bpftool prog
show", because bpftool cannot load the LE bytecode on the BE target
machine. This is Christophe's output [here](https://lore.kernel.org/bpf/0792068b-9aff-d658-5c7d-086e6d394c6c@csgroup.eu/).
>
> So the first fix is to make the Makefile aware of the target endianness
somehow, and to build this ELF with target endianness. But this is not
enough, because when (host) boostrap bpftool opens the ELF to generate
the skeleton from it before building the final (target) bpftool binary,
then bpf_object__check_endianness() in libbpf refuses to open the ELF if
endianness is not the same as on the host [as seen here](https://lore.kernel.org/bpf/21b09e52-142d-92f5-4f8b-e4190f89383b@csgroup.eu/).
>
> The way I see it, we'd need to make sure libbpf can work with ELFs of a
different endianness -- assuming that's doable -- and to pass it an
option to tell whether LE or BE is expected for a given ELF. Which in
turn would require bootstrap bpftool to be aware of the target
endianness.

https://lore.kernel.org/bpf/f0c40278-6355-1e35-cfca-fc28cc791a91@isovalent.com/

**Comment by qmonnet** [comment]
Cc @chantra, just FYI - this is the issue that we discussed earlier today.

**Comment by qmonnet** [comment]
https://lore.kernel.org/bpf/cover.1724313164.git.tony.ambardar@gmail.com/t/#u

**Comment by guidosarducci** [comment]
That patch series was merged with my latest revision. Hopefully the years of cross-endian trauma can now begin to heal... 🤕 

Looking forward to the next libbpf 1.5.0 and bpftool 7.5.0 releases! 🙌
